
object objs[] = {                                                    // pickup update1 update2 
/* 0*/{ "", "", "This object does not exist.\n",
                                                                                    0, 0, 0 },
/* 1*/{ "your", "phone", "The screen is cracked and it doesn't seem to boot.  Maybe the battery is\n"
                         "depleted or broken.  It might still come in handy at a later time.\n",
                                                                                    1, BROKENPHONE_DISPLAY, DEPLETEDPHONE_DISPLAY },
/* 2*/{ "your", "phone", "It booted up, but you can't use it since the screen is cracked.\n",
                                                                                    1, CRACKEDPHONE_DISPLAY, 0 },
/* 3*/{ "your", "phone", "It has a custom display on it, but still doesn't boot.\n"
                         "The battery is depleted or broken.\n",
                                                                                    1, CRACKEDPHONE_JUMPSTART, 0 },
/* 4*/{ "your", "phone", "It's in a working state.\n",                              1, PHONE_NOTE, 0 },
/* 5*/{ "a", "fire", "It lingers; not really dangerous if you keep distance.\n", 
                                                                                    0, 0, 0 },
/* 6*/{ "a", "car", "It looks completely burned out, but you can't take a closer look due to a lingering fire.\n", 
                                                                                    0, CAR_EXTINGUISHER, 0 },
/* 7*/{ "a", "car", "It is burned out.\n", 
                                                                                    0, 0, 0 },
/* 8*/{ "a closed", "gate", "The gate is closed and hasn't been used for a long time.  Maybe there is a key\n"
                            "or another gate to exit.\n", 
                                                                                    0, 0, 0 },
/* 9*/{ "a", "shrubbery", "It's large, prickly and looks unmaintained.\n",
                                                                                    0, SHRUBBERY_HEDGESHEAR_EAST, 0 },
/*10*/{ "a", "shrubbery", "It's large, prickly and looks unmaintained.\n",
                                                                                    0, SHRUBBERY_HEDGESHEAR_WEST, 0 }, // Opposite update
/*11*/{ "a", "car", "Its lights are blinking and it looks unlocked.\n", 
                                                                                    0, 0, 0 },
/*12*/{ "a", "rope", "The rope has a fucking magnet tied to it. HOW DO THEY WORK?\n",
                                                                                    1, ROPE_MAILBOX1, ROPE_MAILBOX2 },
/*13*/{ "a", "lasertag", "When pulling the trigger, it beeps a bit and says \"GOOD LUCK\".\n",
                                                                                    1, LASERTAG_QUICKEY, 0 },
/*14*/{ "a", "lasertag", "You removed the batteries; otherwise, it's in good condition.\n",
                                                                                    1, 0, 0 },
/*15*/{ "some", "batteries", "They came from a working lasertag.\n",
                                                                                    1, BATTERIES_PATCHCABLE, 0 },
/*16*/{ "a", "quickey", "They say it opens everything except doors.\n",
                                                                                    1, QUICKEY_LASERTAG, 0 },
/*17*/{ "an", "extinguisher", "Looks like a normal fire extinguisher. The pressure gauge is green\n"
                              "and the expiry date is still ok.\n",
                                                                                    1, EXTINGUISHER_CAR, 0 },
/*18*/{ "a stone", "mailbox", "It looks like it hasn't been emptied yet.\n",
                                                                                    0, MAILBOX_ROPE1, 0 },
/*19*/{ "a stone", "mailbox", "There still seems to be something in there.\n",
                                                                                    0, MAILBOX_ROPE2, 0 },
/*20*/{ "a stone", "mailbox", "It's empty.\n",
                                                                                    0, 0, 0 },
/*21*/{ "a", "flyer", "It's an advertising brochure from \"JUST LIKE YOUR MOM\". That mom in the"
                      "centerfold looks pretty kinky with that staple in her belly button.\n",
                                                                                    1, 0, 0 },
/*22*/{ "a", "note", "It has a floppy stapled to it.. Well that just made it useless.  The note says:\n"
                     "\"THE NEW CODE IS 0118999881999119725..3\"\n",
                                                                                    1, NOTE_PHONE, 0 },
/*23*/{ "a", "ducat", "It says: \"COINYE\" on it. It might still come in handy, though.\n",
                                                                                    1, DUCAT_VENDINGMACHINE, 0 },
//"The brand says: \"IMPERIAL TOBACCO - WEST\", but is empty except for some weird red keychain.\n"
/*24*/{ "a", "vendingmachine", "It is empty except for some weird red keychain.\n",
                                                                                    0, VENDINGMACHINE_DUCAT, 0 },
/*25*/{ "a", "vendingmachine", "It is empty.\n",
                                                                                    0, 0, 0 },
/*26*/{ "a red", "keychain", "It looks like it is a wireless key fob.\n",
                                                                                    1, KEYFOB_DOOR, 0 }, // infinite use
/*27*/{ "a", "dumpster", "It is locked.\n",
                                                                                    0, DUMPSTER_KEY, 0 },
/*28*/{ "a", "dumpster", "You unlocked it.\n",
                                                                                    0, 0, 0 },
/*29*/{ "a", "tri-angle-key", "It is 3D printed.\n",
                                                                                    1, KEY_DUMPSTER, KEY_JUNCTIONBOX },
/*30*/{ "a", "computer", "It is connected to the 3D printer and currently displays a picture\n"
                         "of a waste container\n",
                                                                                    0, 0, 0 },
/*31*/{ "a", "lockpick-kit", "It looks a bit cheap.\n",
                                                                                    1, LOCKPICK_DOOR, 0 },

/*32*/{ "a", "door", "It says: \"O004\" and has a cheap lock on it.\n",
                                                                                    0, DOOR_LOCKPICK, 0 },
/*33*/{ "an opened", "door", "It says: \"O004\" and has a cheap lock on it.\n",
                                                                                    0, 0, 0 },
/*34*/{ "a small", "display", "This display is not bigger than the display on your phone.\n",
                                                                                    1, DISPLAY_BROKENPHONE, DISPLAY_CRACKEDPHONE },
/*35*/{ "a pair of", "keys", "Regular keys. They could be meant for anything..\n",
                                                                                    1, KEYS_DOOR, KEYS_VAULT },
/*36*/{ "some", "patchcables", "Category 5 cable; wow, that's old. They have cut the 8P8C connector off\n"
                               "and the strands are visible.\n",
                                                                                    1, PATCHCABLE_BATTERIES, 0 },
/*37*/{ "a", "jumpstarter", "You made this from patchcables and some batteries.\n",
                                                                                    1, JUMPSTART_BROKENPHONE, JUMPSTART_DEPLETEDPHONE },
/*38*/{ "a", "hedgeshear", "Apart from some rusty spots, it still shines and looks ok.\n",
                                                                                    1, HEDGESHEAR_SHRUBBERY_EAST, HEDGESHEAR_SHRUBBERY_WEST },
/*39*/{ "a box of", "thermostats", "They are mounted to wooden boards as demo models, but they might be the real\n"
                                   "deal complete with clickety clickety relays in it\n",
                                                                                    1, THERMOSTATS_JUNCTIONBOX, 0 },
/*40*/{ "a classic", "key", "It looks 19th century.\n",
                                                                                    1, OLD_KEY_DOOR, 0 },
/*41*/{ "a carbide", "lantern", "It's in working condition.\n",
                                                                                    1, LIGHT_DARKNESS, 0 },
/*42*/{ "a", "gate", "This gate is motorized.\n", 
                                                                                    0, 0, 0 },
/*43*/{ "a", "junctionbox", "This must be the controller box for the gate that is closed.\n"
                            "It has those little funky tri-angle screw heads on it.\n",
                                                                                    0, JUNCTIONBOX_KEY, 0 },
/*44*/{ "an opened", "junctionbox", "You can connect it to the internet of things using a relay.\n",
                                                                                    0, JUNCTIONBOX_THERMOSTATS, 0 },
/*45*/{ "a modified", "junctionbox", "It's an IoT device, but it needs a code to operate the gate.\n",
                                                                                    0, 0, 0 },
/*46*/{ "an", "elevator", "It doesn't seem to work. Maybe someone tried to put\n"
                          "a rocket-fuel concoction in there.\n",
                                                                                    0, 0, 0 },
/*47*/{ "ten", "pizzaboxes", "They are used, but are all empty\n",
                                                                                    0, 0, 0 },
/*48*/{ "two", "trashcans", "One is full and the other is flowing over with trash.\n",
                                                                                    0, 0, 0 },
/*49*/{ "some", "candy", "It's in a bowl, uncovered.\n",
                                                                                    1, 0, 0 },
/*50*/{ "various", "hardware", "It consists of parts and snippets of gameboys spread across the table.\n",
                                                                                    1, 0, 0 },
/*51*/{ "a", "door", "It seems to be an automatic door but it doesn't move.  It might need power,\n"
                     "or is operated from the other side.\n",
                                                                                    0, 0, 0 },
/*52*/{ "a very thick", "door", "This looks like a vault-like door.  Must be something like a nuclear shelter.\n"
                                "apparently, it's locked.\n",
                                                                                    0, VAULT_KEYS, 0 },
/*53*/{ "a very thick", "door", "This looks like a vault-like door.  Must be something like a nuclear shelter.\n"
                                "It was slided open.\n",
                                                                                    0, 0, 0 },
/*54*/{ "a", "hatch", "It looks like access to crawlspace.  You can't reach the lever.\n",
                                                                                    0, HATCH_STICK, 0 },
/*55*/{ "some", "stick", "It has a hook on it.\n",
                                                                                    1, STICK_HATCH, 0 },
/*56*/{ "a server", "cabinet", "It is open and has some old, dusty equipment in it.  Was this lock picked?\n",
                                                                                    0, 0, 0 },
/*57*/{ "a", "staircase", "This one is intact.\n",
                                                                                    0, 0, 0 },
/*58*/{ "the", "sunrise", "Almost looks as if you were standing here, talking for a long time.\n",
                                                                                    0, 0, 0 },
/*59*/{ "an open", "window", "The window is too high from the outside to get in.\n",
                                                                                    0, 0, 0 },
/*60*/{ "a", "door", "The door, together with the building look old.  Apparently, it's locked.\n",
                                                                                    0, OLD_DOOR_KEY, 0 },
/*61*/{ "a", "door", "The door, together with the building look old.\n",
                                                                                    0, 0, 0 },
/*62*/{ "a", "door", "Apparently, it's locked.\n",
                                                                                    0, DOOR_KEYS, 0 },
/*63*/{ "a", "door", "It's unlocked.\n",
                                                                                    0, 0, 0 },
/*64*/{ "a", "door", "It says: \"Q316\" and is unlocked.\n",
                                                                                    0, 0, 0 },
/*65*/{ "a", "door", "It says: \"L406 ACKSPACE\".\n",
                                                                                    0, DOOR_KEYFOB, 0 },
/*66*/{ "", "dishes", "Hmm, they are probably not cleaned yet.\n",
                                                                                    0, 0, 0 },
/*67*/{ "a", "bottle", "It's a half-empty sprite.\n",
                                                                                    1, 0, 0 },
/*68*/{ "a lot of", "bottles", "There are six Winter Mate, Some Mate cola bottles, a regular Mate and a couple\n"
                               "of beer bottles, all empty\n",
                                                                                    0, 0, 0 },
/*69*/{ "a", "screen", "It says: \"HELLO VICARIOUS, YOU CURRENTLY HAVE DA SYNTAX\". Hmm, strange\n"
                       "notification.\n",
                                                                                    0, 0, 0 },
/*70*/{ "a key", "cabinet", "It is open and empty.  Was this lock picked?\n",
                                                                                    0, 0, 0 },
/*71*/{ "an", "engine", "It is running and driving a belt that leads outside.\n",
                                                                                    0, MACHINE_SPANNER, 0 },
/*72*/{ "an", "engine", "It is not running.\n",
                                                                                    0, 0, 0 },
/*73*/{ "", "darkness", "It's too dark to see anything, really.\n",
                                                                                    0, DARKNESS_LIGHT, 0 },
/*74*/{ "a", "spanner", "You know how the saying goes..\n",
                                                                                    1, SPANNER_MACHINE, 0 },
/*75*/{ "an old", "elevator", "It is driven by the belt running outside to the engine building\n"
                              "You can't take a closer look since you might get stuck in the belt\n",
                                                                                    0, 0, 0 },
/*76*/{ "an old", "elevator", "It stopped working so you can have a better look around.\n",
                                                                                    0, 0, 0 },
/*77*/{ "a modified", "junctionbox", "It's an IoT device, and has opened the gate!\n",
                                                                                    0, 0, 0 },
/*78*/{ "game", "instructions", "NAVIGATING:\n  east\n  west\n  north\n  south\n  up\n  down\n\nINSPECTING:\n  look\n  look [noun]\n  inventory\n\nINTERACTION:\n  take/pickup [noun]\n  drop [noun]\n  use [noun1] [noun2]\n",
                                                                                    2, 0, 0 },
#ifdef DONT_SHIT_YOUR_PANTS
/*79*/{ "", "pills", "It says \"IMODIUM\" on them.\n",
                                                                                    0, 0, 0 },
/*80*/{ "a", "toilet", "Don't shit your pants!\n",
                                                                                    0, 0, 0 },
/*81*/{ "", "pants", "Don't shit your pants!\n",
                                                                                    2, 0, 0 },
/*82*/{ "dirty", "pants", "You shit them.\n",
                                                                                    2, 0, 0 },
/*83*/{ "a pile of", "shit", "The colossal dump you took.\n",
                                                                                    0, 0, 0 },
#endif
};

